# Snapcraft Recipe for the VirusTotal CLI
#
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: Apache-2.0
name: vt-cli
title: VirusTotal CLI (UNOFFICIAL)
summary: Do everything you'd normally do using VirusTotal's web page with this tool.
description: |
  Welcome to the VirusTotal CLI, a tool designed for those who love both VirusTotal and command-line interfaces. With this tool you can do everything you'd normally do using VirusTotal's web page, including:

  * Retrieve information about a file, URL, domain name, IP address, etc.
  * Search for files and URLs using VirusTotal Intelligence query syntax.
  * Download files.
  * Manage your LiveHunt YARA rules.
  * Launch Retrohunt jobs and get their results.

  And much more: https://virustotal.github.io/vt-cli/doc/vt.html

  **Snap maintainer notice:**

  This is NOT an official distribution of the VirusTotal CLI, refer to the snap's own issue tracker for support:

  https://gitlab.com/brlin/vt-cli-snap/-/issues

  The upstream preferred `vt` command is not currently set up by default, you may need to set it up manually by running the following command in a text terminal:

      sudo snap alias vt-cli.vt vt

  To scan files under storage mounted under the `/media`, `/run/media`, and the `/mnt` directories, you need to connect the snap to the `removable-media` snapd security confinement interface by running the following command in a text terminal:

      sudo snap connect vt-cli:removable-media

license: Apache-2.0
source-code: &snap-project-url
  - https://gitlab.com/brlin/vt-cli-snap
website: *snap-project-url
issues: &snap-issue-tracker-url
  - https://gitlab.com/brlin/vt-cli-snap/-/issues
contact: *snap-issue-tracker-url
base: core24
adopt-info: vt-cli
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  riscv64:
  s390x:

plugs:
  dot-vt-toml:
    interface: personal-files
    read:
      - $HOME/.vt.toml

apps:
  vt-cli: &vt-app-defs
    command: bin/vt
    command-chain:
      - bin/snap-maintenance-launcher.sh
    completer: etc/bash_completion.d/vt
    plugs:
      - home
      - removable-media
      - network

  vt: *vt-app-defs

parts:
  vt-cli:
    plugin: go
    source: https://github.com/VirusTotal/vt-cli.git
    source-subdir: .
    build-snaps:
      - go/1.24/stable
    override-pull: "${CRAFT_PROJECT_DIR}/snap/local/override-pull.sh"
    override-build: "${CRAFT_PROJECT_DIR}/snap/local/override-build.sh"

  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
