# Snapcraft Recipe for the VirusTotal CLI
#
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: Apache-2.0
name: vt-cli
title: VirusTotal CLI
summary: Do everything you'd normally do using VirusTotal's web page with this tool.
description: |
  Welcome to the VirusTotal CLI, a tool designed for those who love both VirusTotal and command-line interfaces. With this tool you can do everything you'd normally do using VirusTotal's web page, including:

  * Retrieve information about a file, URL, domain name, IP address, etc.
  * Search for files and URLs using VirusTotal Intelligence query syntax.
  * Download files.
  * Manage your LiveHunt YARA rules.
  * Launch Retrohunt jobs and get their results.

  And much more: https://virustotal.github.io/vt-cli/doc/vt.html

  **Snap maintainer notice:**

  This is NOT an official distribution of the VirusTotal CLI, refer to the snap's own issue tracker for support:

  https://gitlab.com/brlin/vt-cli-snap/-/issues
base: core24
adopt-info: vt-cli
grade: stable
confinement: strict

apps:
  vt-cli: &vt-app-defs
    command: bin/vt
    plugs:
      - home
      - removable-media
      - network

  vt: *vt-app-defs

parts:
  vt-cli:
    plugin: go
    source: https://github.com/VirusTotal/vt-cli.git
    source-subdir: .
    build-snaps:
      - go/1.24/stable
    override-pull: |
      if ! craftctl default; then
        printf \
          'Error: Unable to run the default logic of the pull step.\n' \
          1>&2
        exit 2
      fi

      if ! part_version="$(
        git -C "${CRAFT_PART_SRC}" describe \
          --always \
          --dirty \
          --match='*.*.*' \
          --tags
        )"; then
        printf \
          'Error: Unable to describe the version of the main part.\n' \
          1>&2
        exit 2
      fi
      printf \
        'Info: The version of the main part is determined as %s.\n' \
        "${part_version}" \
        1>&2

      if ! packaging_version="$(
        git -C "${CRAFT_PROJECT_DIR}" describe \
          --always \
          --dirty \
          --abbrev=3
        )"; then
        printf \
          'Error: Unable to describe the packaging version.\n' \
          1>&2
        exit 2
      fi
      printf \
        'Info: The packaging version is determined as %s.\n' \
        "${packaging_version}" \
        1>&2

      snap_version="${part_version}+s${packaging_version}"
      if ! craftctl set version="${snap_version}"; then
        printf \
          'Error: Unable to set the version of the snap.\n' \
          1>&2
        exit 2
      fi
      printf \
        'Info: The version of the snap is set to %s.\n' \
        "${snap_version}" \
        1>&2
